name: Check SpaceX Website

on:
  schedule:
    - cron: "*/1 * * * *"  # Revisa cada 30 minutos
  workflow_dispatch:  # Permite ejecutarlo manualmente desde GitHub Actions

jobs:
  check-website:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalar dependencias
        run: npm install axios

      - name: Ejecutar el bot
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: node index.js

      - name: Guardar cambios si hay actualizaciones
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add last_version.html || true
          git commit -m "🔄 Actualización detectada en SpaceX" || true
          git push || true
